name: PHPUnit

on: [push, pull_request]

jobs:
    phpunit-xdebug-test:
        name: Test with PHPUnit and XDebug
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: php-actions/composer@v5

            - name: PHPUnit Tests
              uses: php-actions/phpunit@v2
              with:
                  version: 9.5.2 # Must match the projects composer version
                  php_version: 8 # Must match the projects composer version
                  #php_extensions: xdebug
                  configuration: phpunit.xml
                  bootstrap: vendor/autoload.php
                  #args: --coverage-html coverage
